providers = ["php"]

[phases.setup]
nixPkgs = ["php82", "php82Packages.composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --no-interaction"]

[start]
cmd = "php -d variables_order=EGPCS -S 0.0.0.0:$PORT -t public public/index.php"
