/* tslint:disable */
/* eslint-disable */
/**
 * Food App API Documentation
 * API documentation for Food App
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@foodapp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

